In [3]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/processed/compteur-one-hot-encoded.csv", index_col=0)
df.head()

,Comptage horaire,Jour,Mois,Année,Heure,Jour_semaine,Jour férié,Vacances scolaires,Nom du compteur_10 avenue de la Grande Armée SE-NO,Nom du compteur_10 boulevard Auguste Blanqui NE-SO,...,Nom du compteur_Totem 64 Rue de Rivoli E-O,Nom du compteur_Totem 64 Rue de Rivoli O-E,Nom du compteur_Totem 73 boulevard de Sébastopol N-S,Nom du compteur_Totem 73 boulevard de Sébastopol S-N,Nom du compteur_Totem 85 quai d'Austerlitz NO-SE,Nom du compteur_Totem 85 quai d'Austerlitz SE-NO,Nom du compteur_Totem Cours la Reine E-O,Nom du compteur_Totem Cours la Reine O-E,Nom du compteur_Voie Georges Pompidou NE-SO,Nom du compteur_Voie Georges Pompidou SO-NE
12886,3166,14,6,2023,14,3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
685401,3070,5,1,2025,15,7,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
667057,3010,20,6,2023,23,2,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
12622,2925,2,6,2023,16,5,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12680,2887,16,6,2023,5,5,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
classes = pd.cut(df['Comptage horaire'], bins=(-1, 2, 7, 15, 26, 39, 54, 74, 107, 170, 250, df['Comptage horaire'].max()), labels=["0-2", "3-7", "8-15", "16-26", "27-39", "40-54", "55-74", "75-107", "108-170", "171-250", "251+"])
classes.value_counts(sort=False, normalize=True)

Comptage horaire
0-2        0.096691
3-7        0.099456
8-15       0.097746
16-26      0.098387
27-39      0.096606
40-54      0.095841
55-74      0.098600
75-107     0.097859
108-170    0.095994
171-250    0.060960
251+       0.061859
Name: proportion, dtype: float64

In [4]:
df = df.drop(columns=['Comptage horaire'])
df['Comptage horaire'] = classes

In [5]:
df.head()

,Jour,Mois,Année,Heure,Jour_semaine,Jour férié,Vacances scolaires,Nom du compteur_10 avenue de la Grande Armée SE-NO,Nom du compteur_10 boulevard Auguste Blanqui NE-SO,Nom du compteur_102 boulevard de Magenta SE-NO,...,Nom du compteur_Totem 64 Rue de Rivoli O-E,Nom du compteur_Totem 73 boulevard de Sébastopol N-S,Nom du compteur_Totem 73 boulevard de Sébastopol S-N,Nom du compteur_Totem 85 quai d'Austerlitz NO-SE,Nom du compteur_Totem 85 quai d'Austerlitz SE-NO,Nom du compteur_Totem Cours la Reine E-O,Nom du compteur_Totem Cours la Reine O-E,Nom du compteur_Voie Georges Pompidou NE-SO,Nom du compteur_Voie Georges Pompidou SO-NE,Comptage horaire
12886,14,6,2023,14,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,251+
685401,5,1,2025,15,7,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,251+
667057,20,6,2023,23,2,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,251+
12622,2,6,2023,16,5,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,251+
12680,16,6,2023,5,5,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,251+

In [6]:
df.to_csv('../data/processed/compteur-classes-one-hot-encoded.csv')

In [4]:
df = pd.read_csv("../data/processed/lieu-compteur-one-hot-encoded.csv", index_col=0)
df.head()

,Jour,Mois,Année,Heure,Jour_semaine,Jour férié,Vacances scolaires,Comptage horaire,Nom du site de comptage_10 avenue de la Grande Armée,Nom du site de comptage_10 boulevard Auguste Blanqui,...,Nom du site de comptage_Pont de la Concorde,Nom du site de comptage_Pont des Invalides,Nom du site de comptage_Pont du Garigliano,Nom du site de comptage_Quai d'Orsay,Nom du site de comptage_Quai des Tuileries,Nom du site de comptage_Totem 64 Rue de Rivoli,Nom du site de comptage_Totem 73 boulevard de Sébastopol,Nom du site de comptage_Totem 85 quai d'Austerlitz,Nom du site de comptage_Totem Cours la Reine,Nom du site de comptage_Voie Georges Pompidou
57773,14,6,2023,14,3,0,0,3166,0,0,...,0,0,0,0,0,0,0,0,0,0
1092998,5,1,2025,15,7,0,1,3070,0,0,...,0,0,0,1,0,0,0,0,0,0
1171485,20,6,2023,23,2,0,0,3024,0,0,...,0,0,0,0,0,0,0,0,1,0
57487,2,6,2023,16,5,0,0,2925,0,0,...,0,0,0,0,0,0,0,0,0,0
57812,16,6,2023,5,5,0,0,2887,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
classes = pd.cut(df['Comptage horaire'], bins=(-1, 3, 9, 18, 31, 46, 64, 86, 115, 155, 230, 450, df['Comptage horaire'].max()), 
                 labels=["0-3", "4-9", "10-18", "19-31", "32-46", "47-64", "65-86", "87-115", "116-155", "156-230", "231-450", "451+"])
classes.value_counts(sort=False, normalize=True)

Comptage horaire
0-3        0.090551
4-9        0.084643
10-18      0.084402
19-31      0.088343
32-46      0.085355
47-64      0.088036
65-86      0.086368
87-115     0.087043
116-155    0.085028
156-230    0.086576
231-450    0.091286
451+       0.042368
Name: proportion, dtype: float64

In [6]:
df = df.drop(columns=['Comptage horaire'])
df['Comptage horaire'] = classes

In [7]:
df.head()

,Jour,Mois,Année,Heure,Jour_semaine,Jour férié,Vacances scolaires,Nom du site de comptage_10 avenue de la Grande Armée,Nom du site de comptage_10 boulevard Auguste Blanqui,Nom du site de comptage_102 boulevard de Magenta,...,Nom du site de comptage_Pont des Invalides,Nom du site de comptage_Pont du Garigliano,Nom du site de comptage_Quai d'Orsay,Nom du site de comptage_Quai des Tuileries,Nom du site de comptage_Totem 64 Rue de Rivoli,Nom du site de comptage_Totem 73 boulevard de Sébastopol,Nom du site de comptage_Totem 85 quai d'Austerlitz,Nom du site de comptage_Totem Cours la Reine,Nom du site de comptage_Voie Georges Pompidou,Comptage horaire
57773,14,6,2023,14,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,451+
1092998,5,1,2025,15,7,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,451+
1171485,20,6,2023,23,2,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,451+
57487,2,6,2023,16,5,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,451+
57812,16,6,2023,5,5,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,451+

In [8]:
df.to_csv('../data/processed/lieu-compteur-classes-one-hot-encoded.csv')